OWN_POSITION_TOPIC = "/revolt/sim/stc/position/hull"
OWN_CURRENT_WAYPOINT_TOPIC = "/revolt/control/los_current_waypoint"
OWN_NEXT_WAYPOINT_TOPIC = "/revolt/control/los_next_waypoint"
OWN_PATH_TOPIC = "/revolt/path"
OWN_VIZ_TOPIC = "/viz/boats"
