FROM ros:jazzy-ros-base-noble

RUN apt update && apt install -y \
  ros-jazzy-navigation2 \
  python3-colcon-common-extensions \
  libx11-6 \
  ros-jazzy-rviz2 \
  ros-jazzy-rqt-image-view \
  ros-jazzy-rqt-plot \
  ros-jazzy-rqt-common-plugins \
  ros-jazzy-rqt-tf-tree
